### ISSUE TITLE
ninja: build stopped, no such file or directory

### ISSUE THREAD

**Issue by monatis** [takeitallsource/openal-android-sample#1]
I get the following error when building this project. If I understand correctly, some scripts refers to 'files/android-sdk', but my sdk is placed in 'C:\Program Files\android-sdk'. Where should I correct this path?

![screenshot 2017-09-06 17 47 39](https://user-images.githubusercontent.com/18634956/30118378-8ee9f5ee-932b-11e7-904b-c8f3181f2b4d.png)

> Determining if the C compiler works failed with the following output:
> Change Dir: C:/Users/Asus/AndroidStudioProjects/openal-android-sample/openAL4Android/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp
> 
> Run Build Command:"C:/Program Files/android-sdk/cmake/3.6.4111459/bin/ninja.exe" "cmTC_2926d"
> [1/2] Building C object CMakeFiles/cmTC_2926d.dir/testCCompiler.c.o
> 
> FAILED: C:\PROGRA~1\ANDROI~1\NDK-BU~1\TOOLCH~1\llvm\prebuilt\WINDOW~1\bin\clang.exe  --target=armv7-none-linux-androideabi --gcc-toolchain="C:/Program Files/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64" --sysroot="C:/Program Files/android-sdk/ndk-bundle/sysroot"   -isystem C:/Program Files/android-sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=9 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -o CMakeFiles/cmTC_2926d.dir/testCCompiler.c.o   -c C:\Users\Asus\AndroidStudioProjects\openal-android-sample\openAL4Android\.externalNativeBuild\cmake\release\armeabi-v7a\CMakeFiles\CMakeTmp\testCCompiler.c
> 
> clang.exe: error: no such file or directory: 'Files/android-sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi'
> 
> 
> ninja: build stopped: subcommand failed.
>

**Comment by monatis** [comment]
I've just found out that spaces in the path to android-sdk breaks ndk build. So I moved my sdk directory to 'C:\android-sdk', and it's working now. Thanks.

**Comment by manfreddiaz** [comment]
@monatis Good to hear it is working now!
